version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: reachmasked-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reachmasked
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d reachmasked" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
